### PR TITLE
Fix: ensure that options and results are only evaluated once

### LINKED ISSUE #23: A procedure inside "=?" sometimes called twice
questionable version 0.10.5 (as used by Codex) and this is minimal case, compiled from the root of questionable:
```Nim
import ./questionable
import ./questionable/results

type
  Block* = ref object of RootObj
    cid*: string

proc make_echo: ?!Block =
  echo "make_echo"
  Block(cid:"1").success

for i in 1..1:
  if cid =? make_echo().?cid:
    echo "outside"
```

its output:
```
make_echo
make_echo
outside
```

Compiled with `nim c -d:danger testQ.nim`

### PR DESCRIPTION
**Pull request by markspanbroek**
fixes #23

### CODE REVIEW

**Comment by markspanbroek** [comment]
This fix is probably interesting for you as well @Menduist.
The code in [nim-quic that replaces questionable](https://github.com/status-im/nim-quic/blob/26b1c76f8574883e385f8650090a74d33cc9d0fa/quic/basics.nim#L13) has the same problem; the optional expression is evaluated more than once.

**Comment by Menduist** [comment]
Thanks, will fix :)

**Comment by Bulat-Ziganshin** [comment]
I didn't do deeper research, but in my example, double evaluation happens only inside a loop. Are you sure that your new tests cover the problematic cases?

**Comment by markspanbroek** [comment]
Yes, I checked that the code from your bug report works.
I'm not sure why you needed the loop to trigger the double evaluation; I got the double evaluation also without the loop.

**Comment by Bulat-Ziganshin** [comment]
I rechecked - you are right, the problem manifests in 0.10.5 even when I delete `for` from my example.

**Pull request merged**
